name: clang-format
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-format:
    name: Check code formatting using clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check clang-format
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: '.'
          extensions: 'c,h'
          clangFormatVersion: 17
          style: Google
